version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=certificates_management_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8888
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
